name: Build Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y intltool libcurl4-gnutls-dev libmpdclient-dev libgtk-3-dev libglib2.0-dev libavahi-client-dev libtagc0-dev libavahi-glib-dev automake autoconf libtool build-essential
    - name: configure
      run: ./autogen.sh
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make install
      run: sudo make install
    - name: make dist
      run: |
        make dist
        mv ario-*.tar.gz ario-latest.tar.gz
    - uses: actions/upload-artifact@v3
      with:
        name: ario-latest.tar.gz
        path: ario-latest.tar.gz