name: Deployment Linux

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y intltool libcurl4-gnutls-dev libmpdclient-dev libgtk-3-dev libglib2.0-dev libavahi-client-dev libtagc0-dev libavahi-glib-dev automake autoconf libtool build-essential
    - name: configure
      run: ./autogen.sh
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make install
      run: sudo make install
    - name: make dist
      run: |
        make dist
    - name: Upload
      uses: actions/upload-release-asset@v1.0.1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ario-${{ github.event.release.tag_name }}.tar.gz
        asset_name: ario-${{ github.event.release.tag_name }}.tar.gz
        asset_content_type: binary/octet-stream